import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import Navbar from "@/components/navbar";
import { Box } from "@chakra-ui/react";
import { Toaster, toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  const { children } = props;
  return (
    <html suppressHydrationWarning className={`${montserrat.variable}`}>
      <body>
        <Provider>
          <Toaster />
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
